# Generated by Django 5.1.7 on 2025-03-21 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0005_employee_age_employee_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.SmallIntegerField(null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contact",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.contact",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.department",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
