# Generated by Django 5.1.7 on 2025-03-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0006_trainee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="compensations",
        ),
        migrations.AddField(
            model_name="employee",
            name="about",
            field=models.CharField(default="text", max_length=10000),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="work_experience",
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name="Compensation",
        ),
    ]
