# Generated by Django 5.1.7 on 2025-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0007_remove_employee_compensations_employee_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="about",
            field=models.CharField(db_index=True, default="text", max_length=10000),
        ),
    ]
