# Generated by Django 5.1.7 on 2025-03-21 16:17

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0008_alter_employee_about"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["about"], name="hr_employee_about_ix"
            ),
        ),
    ]
