# Generated by Django 5.1.7 on 2025-03-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0009_employee_hr_employee_about_ix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="about",
            field=models.CharField(default="text", max_length=10000),
        ),
    ]
